#!/bin/bash

# ScribeFlow Quick Reference - Development Commands

echo "ScribeFlow - Quick Command Reference"
echo "====================================="
echo ""
echo "📦 Setup:"
echo "  npm run install:all              Install frontend + backend dependencies"
echo "  ./setup.sh                       Run interactive setup script"
echo ""
echo "💻 Development:"
echo "  npm run dev                      Start frontend only (port 5173)"
echo "  npm run dev:server               Start backend only (port 3001)"
echo "  npm run dev:full                 Start frontend + backend together"
echo ""
echo "🔨 Build:"
echo "  npm run build                    Build frontend for production"
echo "  npm run build:server             Build backend TypeScript"
echo "  npm run build                    Build both (frontend then backend)"
echo ""
echo "🚀 Production:"
echo "  docker-compose up --build        Deploy full stack with Docker"
echo "  npm run start:server             Start backend in production mode"
echo ""
echo "📁 Key Files:"
echo "  Frontend:"
echo "    - App.tsx                      Main app entry"
echo "    - services/geminiService.ts    Backend API calls"
echo "    - constants.ts                 Configuration (BACKEND_URL)"
echo "  Backend:"
echo "    - server/src/index.ts          Express server"
echo "    - server/src/routes/transcribe.ts"
echo "    - server/src/services/geminiService.ts"
echo ""
echo "⚙️  Configuration:"
echo "  .env                             Frontend environment"
echo "  server/.env                      Backend environment (REQUIRED: GEMINI_API_KEY)"
echo ""
echo "🔐 Security:"
echo "  - Never commit .env files"
echo "  - GEMINI_API_KEY only on backend"
echo "  - Frontend cannot access the key"
echo ""
echo "📊 API Endpoints:"
echo "  POST /api/transcribe             Transcribe audio/video"
echo "  GET /health                      Health check"
echo ""
echo "📚 Documentation:"
echo "  - IMPLEMENTATION_SUMMARY.md      What was implemented"
echo "  - BACKEND_SETUP.md               Backend documentation"
echo "  - PRODUCTION_DEPLOYMENT.md       Deployment guides"
echo "  - NEW_README.md                  Updated project README"
echo ""
echo "🐛 Debugging:"
echo "  docker-compose logs backend -f   Live backend logs"
echo "  curl http://localhost:3001/health    Test backend"
echo ""
echo "✅ First Time Setup:"
echo "  1. npm run install:all"
echo "  2. cp server/.env.example server/.env"
echo "  3. Edit server/.env and add GEMINI_API_KEY"
echo "  4. npm run dev:full"
echo "  5. Visit http://localhost:5173"
